/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tjzDe2fCJDP
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent } from "@/components/ui/card"

export function getStarted() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="space-y-4 text-center">
          <div className="space-y-2">
            <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">How it Works</div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Our Simple 4-Step Process</h2>
            <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Learn how our app can streamline your workflow in just a few simple steps.
            </p>
          </div>
        </div>
        <div className="mt-10 overflow-x-auto">
          <div className="flex gap-6">
            <div className="flex-shrink-0 w-[300px] md:w-[350px] lg:w-[400px]">
              <Card>
                <CardContent className="flex flex-col items-center justify-center gap-4 p-6">
                  <ClipboardIcon className="w-10 h-10 text-primary" />
                  <div className="space-y-1 text-center">
                    <h3 className="text-lg font-semibold">Sign Up and Connect</h3>
                    <p className="text-muted-foreground">Create your account and connect your tools to get started.</p>
                  </div>
                </CardContent>
              </Card>
            </div>
            <div className="flex-shrink-0 w-[300px] md:w-[350px] lg:w-[400px]">
              <Card>
                <CardContent className="flex flex-col items-center justify-center gap-4 p-6">
                  <SettingsIcon className="w-10 h-10 text-primary" />
                  <div className="space-y-1 text-center">
                    <h3 className="text-lg font-semibold">Customize Your Workflow</h3>
                    <p className="text-muted-foreground">Tailor the app to your specific needs and preferences.</p>
                  </div>
                </CardContent>
              </Card>
            </div>
            <div className="flex-shrink-0 w-[300px] md:w-[350px] lg:w-[400px]">
              <Card>
                <CardContent className="flex flex-col items-center justify-center gap-4 p-6">
                  <RocketIcon className="w-10 h-10 text-primary" />
                  <div className="space-y-1 text-center">
                    <h3 className="text-lg font-semibold">Automate Your Workflows</h3>
                    <p className="text-muted-foreground">
                      Set up automated workflows to save time and increase efficiency.
                    </p>
                  </div>
                </CardContent>
              </Card>
            </div>
            <div className="flex-shrink-0 w-[300px] md:w-[350px] lg:w-[400px]">
              <Card>
                <CardContent className="flex flex-col items-center justify-center gap-4 p-6">
                  <TrendingUpIcon className="w-10 h-10 text-primary" />
                  <div className="space-y-1 text-center">
                    <h3 className="text-lg font-semibold">Analyze and Optimize</h3>
                    <p className="text-muted-foreground">
                      Use our analytics to identify areas for improvement and optimize your workflows.
                    </p>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

function ClipboardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="8" height="4" x="8" y="2" rx="1" ry="1" />
      <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
    </svg>
  )
}


function RocketIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" />
      <path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z" />
      <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" />
      <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
    </svg>
  )
}


function SettingsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function TrendingUpIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="22 7 13.5 15.5 8.5 10.5 2 17" />
      <polyline points="16 7 22 7 22 13" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
