/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/gqnxlpQnbt2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
"use client"

import { useState } from "react"
import { Dialog, DialogTrigger, DialogContent, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"

export function Popup() {
  const [open, setOpen] = useState(false)
  return (
    <Dialog open={open} onOpenChange={setOpen} defaultOpen>
      <DialogTrigger asChild>
        <Button variant="default">Open Popup</Button>
      </DialogTrigger>
      <DialogContent className="max-w-lg p-0">
        <div className="flex justify-between items-center p-4 border-b">
          <DialogTitle className="text-lg font-semibold">
            Introducing <span className="font-bold">Upscale</span>
          </DialogTitle>
          {/* <Button variant="ghost" size="icon" onClick={() => setOpen(false)}>
            <DoorClosedIcon className="w-5 h-5" />
          </Button> */}
        </div>
        <div className="bg-black text-white flex items-center justify-center h-48">
          <h2 className="text-xl font-bold">Introducing Ideogram Upscale</h2>
        </div>
        <div className="p-4">
          <DialogDescription className="text-sm text-muted-foreground">
            Enhance every pixel with state-of-the-art detail and photorealism up to a stunning 2K resolution. Create
            professional-quality images with remarkable clarity and sharpness, even in close-ups. Now available for{" "}
            <a href="#" className="underline">
              Ideogram Basic, Plus, and Pro.
            </a>
          </DialogDescription>
          <DialogFooter className="mt-4">
            <Button variant="default">Learn more</Button>
          </DialogFooter>
        </div>
      </DialogContent>
    </Dialog>
  )
}

function DoorClosedIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 20V6a2 2 0 0 0-2-2H8a2 2 0 0 0-2 2v14" />
      <path d="M2 20h20" />
      <path d="M14 12v.01" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
